"use client";import PaymentsPanel from './PaymentsPanel';import {useState,useEffect} from 'react';import {useRouter} from 'next/navigation';
const labels:Record<string,string>={overview:'Overview',verifications:'Verification',workers:'Workers',jobs:'Job requests',assignments:'Assignments',replacements:'Replacements',attendance:'Attendance',payments:'Payments',ledger:'Worker ledger',clients:'Clients',incidents:'Incidents'};
const scope:Record<string,string>={overview:'OPERATIONS',verifications:'VERIFICATION',workers:'OPERATIONS',jobs:'OPERATIONS',assignments:'OPERATIONS',replacements:'OPERATIONS',attendance:'OPERATIONS',payments:'FINANCE',ledger:'FINANCE',clients:'OPERATIONS',incidents:'SUPPORT'};
async function api(path:string,data?:unknown){const r=await fetch('/api/ops/'+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error?.code||'Could not complete action');return d;}
const human=(s:string)=>s.replaceAll('_',' ').replaceAll('.', ' ');
export default function Console({user}:{user:{full_name:string;roles:string[]}}){const router=useRouter();const allowed=Object.keys(labels).filter(s=>user.roles.includes('SUPER_ADMIN')||user.roles.includes(scope[s]));const [section,setSection]=useState(allowed[0]||'overview'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null),[candidates,setCandidates]=useState<any[]>([]),[worker,setWorker]=useState(''),[reason,setReason]=useState(''),[amount,setAmount]=useState(''),[notice,setNotice]=useState('');
 async function load(){setBusy(true);setError('');try{setData(await api('admin/'+section));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{setSelected(null);setCandidates([]);setNotice('');load();},[section]);
 async function action(path:string,body:unknown){setBusy(true);setError('');try{const d=await api(path,body);setNotice('Action saved.');await load();return d;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const fields:Record<string,string[]>={verifications:['type','status','worker_id','created_at'],workers:['user_id','onboarding_status','worker_status','experience_years'],jobs:['engagement_type','status','headcount','start_at'],assignments:['job_id','worker_id','status','assigned_at'],replacements:['reason','status','original_assignment_id','created_at'],attendance:['type','shift_id','reason','server_timestamp'],payments:['method','amount_paise','currency','status'],ledger:['type','amount_paise','currency','worker_id'],clients:['user_id','client_type','onboarding_complete'],incidents:['type','status','description','created_at']};
 function value(row:any,key:string){const v=row[key];if(v===null||v===undefined)return '-';if(key.endsWith('_at'))return new Date(v).toLocaleString();if(key.endsWith('_paise'))return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(v/100);if(key.endsWith('_id'))return String(v).slice(0,8);return String(v);}
 return <div className="ops"><aside className="sidebar"><div className="brand">Labour Youth</div>{allowed.map(s=><button key={s} className={section===s?'selected':''} aria-current={section===s?'page':undefined} onClick={()=>setSection(s)}>{labels[s]}</button>)}</aside><main className="ops-main"><header className="ops-header"><div><span className="eyebrow">Operations workspace</span><h1>{labels[section]}</h1></div><div><span className="muted">{user.full_name} </span><button className="secondary" onClick={async()=>{await fetch('/api/session',{method:'DELETE'});router.refresh();}}>Sign out</button></div></header>{error&&<p className="error" role="alert">{human(error)}. Refresh or check the action details.</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Loading…</p>}{section==='overview'&&data&&<div className="metrics">{Object.entries(data).map(([k,v])=><div className="metric" key={k}><span>{human(k)}</span><strong>{String(v)}</strong></div>)}</div>}{section!=='overview'&&data?.items&&<div className="panel table-wrap"><table><thead><tr>{fields[section]?.map(k=><th key={k} scope="col">{human(k)}</th>)}<th scope="col">Action</th></tr></thead><tbody>{data.items.map((row:any)=><tr key={row.id}>{fields[section]?.map(k=><td key={k}>{k.includes('status')?<span className="tag">{human(value(row,k))}</span>:value(row,k)}</td>)}<td><button className="secondary" onClick={()=>{setSelected(row);setCandidates([]);setReason('');setNotice('');}}>Open</button></td></tr>)}</tbody></table>{data.items.length===0&&<p>No records in this queue yet.</p>}</div>}{section==='payments'&&<PaymentsPanel selected={selected} onChanged={load}/ >}{selected&&<section className="panel detail"><h2 style={{fontSize:26}}>Record details</h2><p className="muted">{selected.id}</p>{section==='verifications'&&<><a className="button secondary" href={'/api/ops/documents/'+selected.document_id} target="_blank" rel="noreferrer">Open private evidence</a><p>Worker: {selected.worker_id}</p></>}{section==='workers'&&<><p>Onboarding: {human(selected.onboarding_status)} · Worker: {human(selected.worker_status)}</p><button className="secondary" onClick={async()=>{try{const d=await api('admin/workers/'+selected.id);setSelected({...selected,...d});}catch(e){setError((e as Error).message);}}}>Load profile</button>{selected.full_name&&<p>{selected.full_name} · {selected.phone_number}</p>}</>}
 <div className="form">{['verifications','workers','replacements','attendance'].includes(section)&&<label>Reason / review notes<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3}/></label>}{section==='verifications'&&selected.status==='PENDING'&&<div className="actions"><button disabled={busy||reason.length<3} onClick={()=>action('admin/verifications/'+selected.id+'/approve',{reason})}>Approve evidence</button><button className="secondary" disabled={busy||reason.length<3} onClick={()=>action('admin/verifications/'+selected.id+'/reject',{reason})}>Request correction</button></div>}{section==='workers'&&<button disabled={busy||reason.length<3||selected.onboarding_status!=='SUBMITTED'} onClick={()=>action('admin/workers/'+selected.id+'/activate',{reason})}>Activate after verification</button>}{section==='attendance'&&selected.type==='MANUAL_REQUEST'&&<div className="actions"><button disabled={busy||reason.length<3} onClick={()=>action('admin/attendance/'+selected.id+'/approve',{reason})}>Approve manual check-in</button><button className="secondary" disabled={busy||reason.length<3} onClick={()=>action('admin/attendance/'+selected.id+'/reject',{reason})}>Reject request</button></div>}
 {['jobs','replacements'].includes(section)&&<><button disabled={busy||(section==='replacements'&&reason.length<3)} onClick={async()=>{const d=await action(section==='jobs'?'admin/jobs/'+selected.id+'/generate-matches':'admin/replacements/'+selected.id+'/rematch',section==='jobs'?{}:{reason});if(d)setCandidates(d.items);}}>Find eligible candidates</button>{candidates.length>0&&<><label>Candidate<select value={worker} onChange={e=>setWorker(e.target.value)}><option value="">Select a worker</option>{candidates.map(c=><option key={c.id} value={c.worker_id}>{c.worker_id.slice(0,8)} · {c.distance_m} m · score {c.final_score}</option>)}</select></label><label>Total agreed worker earnings (rupees)<input type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><p>Confirm this amount with the worker before sending. It is divided across the offered shifts.</p><button disabled={busy||!worker||Number(amount)<=0} onClick={()=>action('admin/jobs/'+(section==='jobs'?selected.id:selected.job_id)+'/offers',{worker_id:worker,agreed_worker_amount_paise:Math.round(Number(amount)*100),expires_at:new Date(Date.now()+30*60000).toISOString(),replacement_request_id:section==='replacements'?selected.id:null})}>Send work offer</button></>}</>}
 </div><button className="secondary" style={{marginTop:24}} onClick={()=>setSelected(null)}>Close details</button></section>}<button className="secondary" style={{marginTop:24}} disabled={busy} onClick={load}>Refresh</button></main></div>;
}
