import {useState} from 'react';import * as Location from 'expo-location';import {Linking,View} from 'react-native';import {Field,Button,Copy,ErrorBox} from './ui';import {useSession} from './session';import {useResource} from './hooks';
// GPS stays for worker check-in and going online (Decision 10); hirers share a Google Maps link instead (Decision 21).
export async function position(){const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')throw new Error('permissionDenied');return Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});}
export const emptyAddress={label:'',line1:'',locality:'',state:'',postal_code:'',city_id:'',maps_url:''};
export const MAPS_HOME='https://www.google.com/maps';
export function MapsLinkField({value,onChange,error}:{value:string;onChange:(v:string)=>void;error?:string}){const {t}=useSession();const [failure,setFailure]=useState('');
 return <View style={{gap:12}}><Field label={t('mapsLink')} value={value} onChangeText={onChange} autoCapitalize="none" autoCorrect={false} keyboardType="url" placeholder="https://maps.app.goo.gl/..." hint={t('mapsLinkHelp')} error={error}/><Button secondary label={t('openGoogleMaps')} onPress={async()=>{try{await Linking.openURL(MAPS_HOME);}catch{setFailure('UNEXPECTED_ERROR');}}}/><ErrorBox code={failure}/></View>;}
export function LocationForm({value,onChange,errors={}}:{value:typeof emptyAddress;onChange:(v:typeof emptyAddress)=>void;errors?:Record<string,string>}){const {t}=useSession();const {data}=useResource('/locations');
 return <View style={{gap:16}}>{data?.cities.map((c:any)=><Button key={c.id} secondary label={(value.city_id===c.id?'✓ ':'')+c.name} onPress={()=>onChange({...value,city_id:c.id,state:c.state})}/>)}{(['label','line1','locality','state','postal_code'] as const).map((k,i)=><Field key={k} label={t(['addressLabel','addressLine','locality','state','postalCode'][i])} value={value[k]} error={errors[k]} onChangeText={v=>onChange({...value,[k]:v})} keyboardType={k==='postal_code'?'number-pad':'default'}/>)}<MapsLinkField value={value.maps_url} error={errors.maps_url} onChange={v=>onChange({...value,maps_url:v})}/></View>;}
