import React,{useState} from 'react';
import {Image,View,Text,Pressable,TextInput,StyleSheet,ScrollView,KeyboardAvoidingView,Platform,ActivityIndicator,TextInputProps} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useSession} from './session';
export const fonts={display:'Anton_400Regular',body:'OpenSans_400Regular',bodyBold:'OpenSans_600SemiBold'};
// Owner palette (Decision 20), light theme: Onyx headings and primary actions, Carbon Black strong text, Gunmetal outlines,
// Charcoal body copy, Dim Grey captions, on off-white and white surfaces; brass is the single accent.
export const colors={paper:'#F4F4F2',white:'#FFFFFF',soft:'#ECEDEC',line:'#DADCDD',lineStrong:'#35393C',quiet:'#646B71',ink:'#0B0C0C',text:'#1C1E20',muted:'#555B60',onInk:'#FFFFFF',accent:'#C9A15A',accentText:'#7A5C22',onAccent:'#0B0C0C',blue:'#35393C',danger:'#B3261E',dangerBg:'#FBEAE8'};
export function Screen({title,subtitle,children,safeTop=false}:{title:string;subtitle?:string;children:React.ReactNode;safeTop?:boolean}){
 return <SafeAreaView style={{flex:1,backgroundColor:colors.paper}} edges={safeTop?['top','bottom','left','right']:['bottom','left','right']}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><View style={s.brandBar}><Image source={require('../assets/logo.png')} resizeMode="contain" accessibilityLabel="Labour Youth" style={s.logo}/></View><View style={s.heading}><Text accessibilityRole="header" style={s.title}>{title}</Text>{subtitle&&<Text style={s.body}>{subtitle}</Text>}</View>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
export function Button({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void|Promise<unknown>;secondary?:boolean;disabled?:boolean}){
 const [busy,setBusy]=useState(false);
 return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled:disabled||busy,busy}} disabled={disabled||busy} onPress={async()=>{setBusy(true);try{await onPress();}finally{setBusy(false);}}} style={({pressed})=>[s.button,secondary&&s.secondary,(pressed||disabled||busy)&&{opacity:0.6}]}>{busy?<ActivityIndicator color={secondary?colors.ink:colors.onInk}/>:<Text style={[s.buttonText,secondary&&{color:colors.ink}]}>{label}</Text>}</Pressable>;
}
export function Field({label,error,hint,...props}:TextInputProps&{label:string;error?:string;hint?:string}){return <View style={{gap:8}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} accessibilityHint={error||hint} placeholderTextColor={colors.quiet} style={[s.input,!!error&&{borderColor:colors.danger,borderWidth:2}]} {...props}/>{error?<Text accessibilityLiveRegion="polite" style={{fontFamily:fonts.bodyBold,fontSize:14,color:colors.danger}}>{error}</Text>:hint?<Text style={{fontFamily:fonts.body,fontSize:14,color:colors.quiet}}>{hint}</Text>:null}</View>;}
export function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>;}
export function Copy({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <Text style={[s.body,strong&&{fontFamily:fonts.bodyBold,color:colors.ink}]}>{children}</Text>;}
export function ErrorBox({code}:{code:string}){const {t}=useSession();return code?<View accessibilityRole="alert" accessibilityLiveRegion="polite" style={s.error}><Text style={{fontFamily:fonts.body,color:colors.danger,fontSize:16}}>{t(code)}</Text></View>:null;}
export function Chip({label,selected,onPress}:{label:string;selected?:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{selected:!!selected}} onPress={onPress} style={[s.chip,selected&&s.chipOn]}><Text style={[s.chipText,selected&&{color:colors.onInk}]}>{label}</Text></Pressable>;}
export function Empty({text}:{text:string}){return <Card><Copy>{text}</Copy></Card>;}
export function Badge({status}:{status:string}){const {t}=useSession();return <View style={s.badge}><Text style={{fontFamily:fonts.bodyBold,color:colors.ink}}>{t(status)}</Text></View>;}
export const s=StyleSheet.create({chip:{minHeight:44,paddingVertical:10,paddingHorizontal:16,borderRadius:22,borderWidth:1,borderColor:colors.line,backgroundColor:colors.white,justifyContent:'center'},chipOn:{backgroundColor:colors.ink,borderColor:colors.ink},chipText:{fontFamily:fonts.bodyBold,fontSize:15,color:colors.ink},bigButton:{minHeight:84,borderRadius:16,padding:18,justifyContent:'center'},bigText:{fontFamily:fonts.bodyBold,fontSize:20,color:colors.onInk},brandBar:{flexDirection:'row',alignItems:'center'},logo:{width:84,height:64,tintColor:colors.ink},page:{padding:24,paddingBottom:40,gap:20,width:'100%',maxWidth:680,alignSelf:'center'},heading:{gap:12,paddingTop:12,paddingBottom:8},title:{fontFamily:fonts.display,fontSize:32,lineHeight:40,color:colors.ink,letterSpacing:0.2},body:{fontFamily:fonts.body,fontSize:16,lineHeight:25,color:colors.muted},label:{fontFamily:fonts.bodyBold,fontSize:15,color:colors.ink},input:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,minHeight:52,padding:14,fontFamily:fonts.body,fontSize:17,color:colors.ink},button:{minHeight:54,backgroundColor:colors.ink,paddingVertical:16,paddingHorizontal:20,borderRadius:14,alignItems:'center',justifyContent:'center'},buttonText:{fontFamily:fonts.bodyBold,fontSize:17,color:colors.onInk,textAlign:'center'},secondary:{backgroundColor:'transparent',borderWidth:1,borderColor:colors.lineStrong},card:{backgroundColor:colors.white,borderRadius:20,borderWidth:1,borderColor:colors.line,padding:20,gap:12},error:{padding:16,borderRadius:12,backgroundColor:colors.dangerBg},badge:{alignSelf:'flex-start',paddingVertical:8,paddingHorizontal:12,borderRadius:30,backgroundColor:colors.soft},row:{flexDirection:'row',gap:12,flexWrap:'wrap'}});
