import {useState,useEffect} from 'react';import {router,useLocalSearchParams,Redirect} from 'expo-router';import {Platform,View} from 'react-native';import DateTimePicker from '@react-native-community/datetimepicker';import AsyncStorage from '@react-native-async-storage/async-storage';import {Screen,Card,Copy,Field,Button,ErrorBox} from '../../src/ui';import {useSession} from '../../src/session';import {api} from '../../src/api';import {useResource,errorCode} from '../../src/hooks';
export default function NewRequest(){const {service_id}=useLocalSearchParams<{service_id:string}>();const {t,user}=useSession();const services=useResource('/services'),locations=useResource('/locations'),addresses=useResource('/addresses');const [step,setStep]=useState(0),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[picker,setPicker]=useState<'date'|'time'|null>(null),[jobId,setJobId]=useState('');
 const [f,set]=useState({service_id:service_id||'',engagement_type:'HOURLY',headcount:'1',date:new Date(Date.now()+86400000).toISOString().slice(0,10),startTime:'09:00',hours:'4',days:'2',address_id:'',service_area_id:'',budget:'',notes:'',requirements:{} as Record<string,string>});
 const key='ly.draft.'+user?.id;
 useEffect(()=>{AsyncStorage.getItem(key).then(s=>{if(s){const v=JSON.parse(s);set({...v,service_id:service_id||v.service_id});}setLoaded(true);}).catch(()=>setLoaded(true));},[key]);
 useEffect(()=>{if(loaded)AsyncStorage.setItem(key,JSON.stringify(f)).catch(()=>{});},[f,loaded,key]);
 if(!user?.roles.includes('CLIENT'))return <Redirect href="/"/>;
 const update=(k:keyof typeof f,v:string)=>set({...f,[k]:v});
 function schedule(){const start=new Date(f.date+'T'+f.startTime+':00');const count=['FIXED_TERM','MONTHLY'].includes(f.engagement_type)?Number(f.days):1;if(!Number.isInteger(count)||count<1||count>62||!Number.isFinite(start.getTime())||Number(f.hours)<=0||Number(f.hours)>24)throw new Error('VALIDATION_ERROR');return Array.from({length:count},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return {start_at:d.toISOString(),end_at:new Date(d.getTime()+Number(f.hours)*3600000).toISOString()};});}
 const next=()=>{setError('');try{if(step===0&&(!f.service_id||!Number.isInteger(Number(f.headcount))||Number(f.headcount)<1))throw new Error();if(step===2)schedule();if(step===3&&(!f.address_id||!f.service_area_id))throw new Error();setStep(step+1);}catch{setError('VALIDATION_ERROR');}};
 return <Screen title={t(step===5?'reviewRequest':'newRequest')} subtitle={`${step+1} / 6`}>
 {step===0&&<><Copy strong>{t('service')}</Copy>{services.data?.items.map((s:any)=><Button key={s.id} secondary label={(f.service_id===s.id?'✓ ':'')+s.name} onPress={()=>update('service_id',s.id)}/>)}<Copy strong>{t('engagement')}</Copy>{['HOURLY','DAILY','FIXED_TERM','MONTHLY'].map(e=><Button key={e} secondary label={(f.engagement_type===e?'✓ ':'')+t(e)} onPress={()=>set({...f,engagement_type:e,days:e==='MONTHLY'?'30':e==='FIXED_TERM'?'2':'1',hours:e==='HOURLY'?'4':'8'})}/>)}<Field label={t('headcount')} value={f.headcount} onChangeText={v=>update('headcount',v)} keyboardType="number-pad"/></>}
 {step===1&&<>{Object.entries((services.data?.items.find((item:any)=>item.id===f.service_id) as any)?.requirement_schema?.properties||{}).map(([name,schema])=>{const rule=schema as any;return <Card key={name}><Copy strong>{t(name)}</Copy>{rule.enum?rule.enum.map((choice:string)=><Button key={choice} secondary label={(f.requirements[name]===choice?'✓ ':'')+t(choice)} onPress={()=>set({...f,requirements:{...f.requirements,[name]:choice}})}/>):<Field label={t(name)} value={f.requirements[name]||''} keyboardType={rule.type==='integer'?'number-pad':'default'} onChangeText={v=>set({...f,requirements:{...f.requirements,[name]:v}})}/>}</Card>;})}</>}
 {step===2&&<><Copy>{t('scheduleHelp')}</Copy>{Platform.OS==='web'?<><Field label={t('date')} value={f.date} onChangeText={v=>update('date',v)}/><Field label={t('startTime')} value={f.startTime} onChangeText={v=>update('startTime',v)}/></>:<><Button secondary label={t('date')+' · '+f.date} onPress={()=>setPicker('date')}/><Button secondary label={t('startTime')+' · '+f.startTime} onPress={()=>setPicker('time')}/>{picker&&<DateTimePicker value={new Date(f.date+'T'+f.startTime+':00')} mode={picker} onChange={(_,date)=>{if(date){if(picker==='date')update('date',date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0'));else update('startTime',String(date.getHours()).padStart(2,'0')+':'+String(date.getMinutes()).padStart(2,'0'));}setPicker(null);}}/>}</>}<Field label={t('hours')} value={f.hours} keyboardType="decimal-pad" onChangeText={v=>update('hours',v)}/>{['FIXED_TERM','MONTHLY'].includes(f.engagement_type)&&<Field label={t('days')} value={f.days} keyboardType="number-pad" onChangeText={v=>update('days',v)}/>}</>}
 {step===3&&<><Copy strong>{t('locations')}</Copy>{locations.data?.service_areas.map((a:any)=><Button key={a.id} secondary label={(f.service_area_id===a.id?'✓ ':'')+a.name} onPress={()=>update('service_area_id',a.id)}/>)}{addresses.data?.items.map((a:any)=><Button key={a.id} secondary label={(f.address_id===a.id?'✓ ':'')+a.label+' · '+a.line1} onPress={()=>update('address_id',a.id)}/>)}<Button secondary label={t('clientSetup')} onPress={()=>router.push('/shared/client-setup')}/></>}
 {step===4&&<><Field label={t('budget')} value={f.budget} onChangeText={v=>update('budget',v)} keyboardType="decimal-pad"/><Copy>{t('quoteHelp')}</Copy><Field label={t('notes')} multiline value={f.notes} onChangeText={v=>update('notes',v)}/></>}
 {step===5&&<Card><Copy strong>{services.data?.items.find((s:any)=>s.id===f.service_id)?.name}</Copy><Copy>{t(f.engagement_type)} · {f.headcount} · {f.hours}h</Copy><Copy>{addresses.data?.items.find((a:any)=>a.id===f.address_id)?.line1}</Copy>{schedule().map(w=><Copy key={w.start_at}>{new Date(w.start_at).toLocaleString()} – {new Date(w.end_at).toLocaleTimeString()}</Copy>)}<Copy>{t('quoteHelp')}</Copy><Copy>{f.notes}</Copy></Card>}
 <ErrorBox code={error||services.error||locations.error||addresses.error}/><Button label={t(step===5?'submitRequest':'continue')} onPress={step===5?async()=>{try{let id=jobId;if(!id){const j=await api('/jobs','POST',{service_id:f.service_id,service_area_id:f.service_area_id,address_id:f.address_id,engagement_type:f.engagement_type,headcount:Number(f.headcount),schedule:schedule(),budget_max:f.budget?Math.round(Number(f.budget)*100):null,currency:'INR',notes:f.notes,requirements:Object.fromEntries(Object.entries(f.requirements).filter(([,value])=>value!=='' ).map(([name,value])=>[name,(services.data?.items.find((item:any)=>item.id===f.service_id) as any)?.requirement_schema?.properties?.[name]?.type==='integer'?Number(value):value])),recurring_metadata:{timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}});id=j.id;setJobId(id);}await api('/jobs/'+id+'/submit','POST');await AsyncStorage.removeItem(key);router.replace({pathname:'/shared/job/[id]',params:{id}});}catch(e){setError(errorCode(e));}}:next}/>{step>0&&<Button secondary label={t('back')} onPress={()=>setStep(step-1)}/>}</Screen>;
}
