import {useEffect,useState} from 'react';import {router,Redirect} from 'expo-router';import {View} from 'react-native';import {Screen,Card,Copy,Field,Button,ErrorBox,Chip} from '../../src/ui';import {useSession} from '../../src/session';import {api} from '../../src/api';import {useResource,errorCode} from '../../src/hooks';import {position} from '../../src/LocationForm';
export default function QuickPost(){const {t,locale,user}=useSession();const services=useResource('/services'),areas=useResource('/locations'),places=useResource('/localities');const [service,setService]=useState(''),[place,setPlace]=useState(''),[headcount,setHeadcount]=useState('1'),[wage,setWage]=useState(''),[tomorrow,setTomorrow]=useState(false),[time,setTime]=useState('08:00'),[hours,setHours]=useState('8'),[notes,setNotes]=useState(''),[error,setError]=useState(''),[rate,setRate]=useState<any>(null),[sent,setSent]=useState<number|null>(null);
 useEffect(()=>{setRate(null);if(service)api('/wages/benchmark?service_id='+service).then(setRate).catch(()=>{});},[service]);
 if(!user?.roles.includes('CLIENT'))return <Redirect href="/"/>;
 async function post(){setError('');try{const area=areas.data?.service_areas?.[0];const count=Number(headcount),rupees=Number(wage),h=Number(hours);const [hh,mm]=time.split(':').map(Number);if(!service||!area||!Number.isInteger(count)||count<1||!(rupees>0)||!Number.isInteger(h)||h<1||h>16||!(hh>=0&&hh<24&&mm>=0&&mm<60))throw new Error('VALIDATION_ERROR');const start=new Date();if(tomorrow)start.setDate(start.getDate()+1);start.setHours(hh,mm,0,0);const p=await position();const j=await api('/jobs/quick','POST',{service_id:service,service_area_id:area.id,latitude:p.coords.latitude,longitude:p.coords.longitude,locality:place,start_at:start.toISOString(),hours:h,headcount:count,wage_per_day_paise:Math.round(rupees*100),notes});setSent(j.notified_workers);router.replace({pathname:'/shared/job/[id]',params:{id:j.id}});}catch(e){setError(e instanceof Error&&e.message==='permissionDenied'?'permissionDenied':e instanceof Error&&e.message==='VALIDATION_ERROR'?'VALIDATION_ERROR':errorCode(e));}}
 return <Screen title={t('quickPost')} subtitle={t('quickPostCopy')}>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{services.data?.items.map((s:any)=><Chip key={s.id} label={locale==='hi'?s.name_hi:s.name} selected={service===s.id} onPress={()=>setService(s.id)}/>)}</View>
  {rate&&rate.median_paise!==null&&<Card><Copy strong>{t('marketRate')}</Copy><Copy>{'Rs '+Math.round(rate.min_paise/100)+' to Rs '+Math.round(rate.max_paise/100)+' · '+t('marketRateRange')+': Rs '+Math.round(rate.median_paise/100)}</Copy></Card>}
  <Field label={t('workersNeeded')} keyboardType="number-pad" value={headcount} onChangeText={setHeadcount}/>
  <Field label={t('dailyWage')} keyboardType="number-pad" value={wage} onChangeText={setWage}/>
  <Copy strong>{t('startDay')}</Copy><View style={{flexDirection:'row',gap:8}}><Chip label={t('today')} selected={!tomorrow} onPress={()=>setTomorrow(false)}/><Chip label={t('tomorrow')} selected={tomorrow} onPress={()=>setTomorrow(true)}/></View>
  <Field label={t('startTime')} value={time} onChangeText={setTime} autoCapitalize="none"/>
  <Field label={t('hoursOfWork')} keyboardType="number-pad" value={hours} onChangeText={setHours}/>
  <Copy strong>{t('locality')}</Copy><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{places.data?.items.map((p:any)=><Chip key={p.id} label={locale==='hi'?p.name_hi:p.name} selected={place===p.name} onPress={()=>setPlace(place===p.name?'':p.name)}/>)}</View>
  <Copy>{t('useLocationNote')}</Copy>
  <Field label={t('notes')} value={notes} onChangeText={setNotes} multiline/>
  <ErrorBox code={error}/>{sent!==null&&<Copy>{t('notifiedWorkers')+': '+sent}</Copy>}
  <Button label={t('postWork')} onPress={post}/>
 </Screen>;}
