import {useState,useEffect} from 'react';import {router,Redirect} from 'expo-router';import * as DocumentPicker from 'expo-document-picker';import {Platform} from 'react-native';import {Screen,Field,Button,ErrorBox,Copy,Card} from '../../src/ui';import {useSession,homeFor} from '../../src/session';import {api} from '../../src/api';import {errorCode,useResource} from '../../src/hooks';
const steps=['basic','photo','services','experience','languages','locations','availability','identity','police','payout'];
export default function Setup(){const {user,t,reload}=useSession();const {data:profile,reload:load}=useResource('/worker/profile');const {data:catalog}=useResource('/services');const {data:locations}=useResource('/locations');const [index,setIndex]=useState(0),[text,setText]=useState(''),[selected,setSelected]=useState<string[]>([]),[doc,setDoc]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false);const step=steps[index];
 useEffect(()=>{if(profile&&!ready){const i=steps.findIndex(s=>!(s in profile.progress));setIndex(i<0?steps.length:i);setReady(true);}},[profile,ready]);
 useEffect(()=>{setText(step==='basic'?user?.full_name||'':String(profile?.progress?.[step]?.years??''));setSelected(step==='services'?profile?.progress?.services?.service_ids||[]:step==='languages'?profile?.progress?.languages?.codes||[]:profile?.progress?.locations?.service_area_ids||[]);setDoc(profile?.progress?.[step]?.document_id||'');setError('');},[step]);
 if(!user)return <Redirect href="/"/>;
 const toggle=(id:string)=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
 async function upload(){try{const file=await DocumentPicker.getDocumentAsync({type:step==='photo'?['image/jpeg','image/png']:['image/jpeg','image/png','application/pdf'],copyToCacheDirectory:true});if(file.canceled)return;const asset=file.assets[0];const form=new FormData();form.append('purpose',step.toUpperCase());if(Platform.OS==='web'){form.append('file',await (await fetch(asset.uri)).blob(),asset.name);}else form.append('file',{uri:asset.uri,name:asset.name,type:asset.mimeType} as any);const d=await api('/documents','POST',form);setDoc(d.id);if(step!=='photo')await api('/worker/verifications','POST',{type:step.toUpperCase(),document_id:d.id});}catch(e){setError(errorCode(e));}}
 async function save(){try{let data:any={};if(step==='basic')data={full_name:text};if(step==='photo')data={document_id:doc};if(step==='services')data={service_ids:selected};if(step==='experience')data={years:Number(text)};if(step==='languages')data={codes:selected};if(step==='locations')data={service_area_ids:selected};if(step==='availability')await api('/worker/availability','PUT',{online:false,service_area_id:profile.progress.locations.service_area_ids[0],radius_m:15000});await api('/worker/onboarding/'+step,'PUT',{data});await load();setIndex(index+1);}catch(e){setError(errorCode(e));}}
 return <Screen title={t('setup')} subtitle={t('savedProgress')}><Copy>{Math.min(index+1,steps.length)} / {steps.length}</Copy>{index<steps.length?<><Card><Copy strong>{t(step)}</Copy>{step==='basic'&&<Field label={t('full_name')} value={text} onChangeText={setText}/>} {step==='experience'&&<Field label={t('years')} keyboardType="number-pad" value={text} onChangeText={setText}/>} {['photo','identity','police'].includes(step)&&<><Button secondary label={t('chooseFile')} onPress={upload}/>{!!doc&&<Copy>{t('fileReady')}</Copy>}</>}{step==='services'&&catalog?.items.map((s:any)=><Button key={s.id} secondary label={(selected.includes(s.id)?'✓ ':'')+s.name} onPress={()=>toggle(s.id)}/>)}{step==='languages'&&['hi','en'].map(s=><Button key={s} secondary label={(selected.includes(s)?'✓ ':'')+(s==='hi'?'हिन्दी':'English')} onPress={()=>toggle(s)}/>)}{step==='locations'&&locations?.service_areas.map((s:any)=><Button key={s.id} secondary label={(selected.includes(s.id)?'✓ ':'')+s.name} onPress={()=>toggle(s.id)}/>)}{step==='availability'&&<Copy>{t('availabilitySetupHelp')}</Copy>}{step==='payout'&&<Copy>{t('payoutHelp')}</Copy>}</Card><ErrorBox code={error}/><Button label={t('save')} onPress={save}/>{index>0&&<Button secondary label={t('back')} onPress={()=>setIndex(index-1)}/>}</>:<><Copy>{t('savedProgress')}</Copy><ErrorBox code={error}/><Button label={t('submitProfile')} onPress={async()=>{try{await api('/worker/onboarding/submit','POST');router.replace(homeFor(await reload()) as any);}catch(e){setError(errorCode(e));}}}/><Button secondary label={t('back')} onPress={()=>setIndex(steps.length-1)}/></>}</Screen>;
}
