import {useCallback,useEffect,useState} from 'react';import {View,Text,Pressable,ScrollView,Image,Linking} from 'react-native';import {SafeAreaView,useSafeAreaInsets} from 'react-native-safe-area-context';import {Ionicons} from '@expo/vector-icons';import {router} from 'expo-router';import {Button,Card,Copy,Empty,ErrorBox,colors,fonts} from '../../src/ui';import {api} from '../../src/api';import {useSession} from '../../src/session';import {errorCode} from '../../src/hooks';
const SHOWN=8;
const INSTAGRAM='https://www.instagram.com/labour.youth/';
// Published figures only (same sources as the website); tapping a card opens its source.
const STATS=[
 {v:'30.68 crore',k:'statEshram',src:'Ministry of Labour, Mar 2025',url:'https://newsonair.gov.in/over-30-crore-unorganised-workers-registered-on-e-shram-portal'},
 {v:'~30 crore',k:'statBlueCollar',src:'Deloitte India, 2025',url:'https://www.deloitte.com/in/en/about/press-room/blue-collar-wages-rise-5-6-percent-annually.html'},
 {v:'+10%',k:'statHiring',src:'Deloitte India, 2025',url:'https://www.deloitte.com/in/en/about/press-room/blue-collar-wages-rise-5-6-percent-annually.html'},
 {v:'2.35 crore',k:'statGig',src:'NITI Aayog, 2022',url:'https://www.governancenow.com/news/regular-story/gig-workforce-expected-to-expand-to-235-crore-by-202930'},
];
const OFFERS=[['time-outline','offerDaily','offerDailyCopy'],['calendar-outline','offerContract','offerContractCopy'],['briefcase-outline','offerPermanent','offerPermanentCopy']] as const;
export default function GuestHome(){const {t,locale,setLocale}=useSession();const insets=useSafeAreaInsets();const [tab,setTab]=useState<'work'|'workers'>('work'),[service,setService]=useState(''),[services,setServices]=useState<any[]>([]),[more,setMore]=useState(false),[items,setItems]=useState<any[]|null>(null),[error,setError]=useState('');
 const hi=locale==='hi';
 useEffect(()=>{api('/services').then(r=>setServices([...r.items.filter((x:any)=>x.slug!=='other'),...r.items.filter((x:any)=>x.slug==='other')])).catch(()=>{});},[]);
 const load=useCallback(async()=>{setError('');setItems(null);try{const q=service?'?service_id='+service:'';setItems((await api('/public/'+(tab==='work'?'jobs':'workers')+q)).items);}catch(e){setError(errorCode(e));setItems([]);}},[tab,service]);
 useEffect(()=>{load();},[load]);
 const register=()=>router.push('/(public)/register');
 const tiles=more?services:services.slice(0,SHOWN);
 const role=(label:string,icon:string,bg:string,fg:string,go:()=>void)=><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={go} style={({pressed})=>({flex:1,minHeight:104,borderRadius:18,padding:16,justifyContent:'space-between',backgroundColor:bg,borderWidth:1,borderColor:bg,opacity:pressed?0.85:1})}><Ionicons name={icon as any} size={28} color={fg}/><Text style={{fontFamily:fonts.bodyBold,fontSize:18,color:fg}}>{label}</Text></Pressable>;
 return <SafeAreaView edges={['top','left','right']} style={{flex:1,backgroundColor:colors.paper}}>
  <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20,paddingTop:4}}>
   <Image source={require('../../assets/logo.png')} resizeMode="contain" accessibilityLabel="Labour Youth" style={{width:72,height:52,tintColor:colors.ink}}/>
   <Pressable accessibilityRole="button" accessibilityLabel={hi?'English':'हिन्दी'} onPress={()=>setLocale(hi?'en':'hi')} style={{minHeight:44,paddingHorizontal:16,borderRadius:22,borderWidth:1,borderColor:colors.line,backgroundColor:colors.white,justifyContent:'center'}}><Text style={{fontFamily:fonts.bodyBold,fontSize:15,color:colors.ink}}>{hi?'English':'हिन्दी'}</Text></Pressable>
  </View>
  <ScrollView contentContainerStyle={{padding:20,paddingBottom:120,gap:20,width:'100%',maxWidth:680,alignSelf:'center'}}>
   <View style={{gap:8}}><View style={{flexDirection:'row',alignItems:'center',gap:6}}><Ionicons name="location-outline" size={16} color={colors.accentText}/><Text style={{fontFamily:fonts.bodyBold,fontSize:14,color:colors.accentText}}>{t('cityName')}</Text></View><Text accessibilityRole="header" style={{fontFamily:fonts.display,fontSize:36,lineHeight:44,color:colors.text,letterSpacing:0.2}}>{t('guestTitle')}</Text><Copy>{t('guestCopy')}</Copy></View>
   <View style={{flexDirection:'row',gap:12}}>{role(t('heroWork'),'briefcase-outline',colors.accent,colors.onAccent,register)}{role(t('heroHire'),'people-outline',colors.ink,colors.onInk,register)}</View>
   <View style={{flexDirection:'row',gap:8,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.line,paddingVertical:16}}>{[['shield-checkmark','trustVerifiedShort'],['cash-outline','trustWageShort'],['heart-outline','trustFreeShort']].map(([icon,k])=><View key={k} style={{flex:1,alignItems:'center',gap:6}}><Ionicons name={icon as any} size={22} color={colors.accentText}/><Text style={{fontFamily:fonts.body,fontSize:12,textAlign:'center',color:colors.muted}}>{t(k)}</Text></View>)}</View>
   {services.length>0&&<View style={{gap:12}}><Text style={{fontFamily:fonts.bodyBold,fontSize:18,color:colors.text}}>{t('popularServices')}</Text>
    <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{tiles.map(s=>{const on=service===s.id;return <Pressable key={s.id} accessibilityRole="button" accessibilityLabel={hi?s.name_hi:s.name} accessibilityState={{selected:on}} onPress={()=>setService(on?'':s.id)} style={{width:'23.5%',minHeight:92,alignItems:'center',justifyContent:'center',gap:8,padding:6,borderRadius:16,borderWidth:1,borderColor:on?colors.ink:colors.line,backgroundColor:colors.white}}><View style={{width:40,height:40,borderRadius:20,backgroundColor:on?colors.ink:colors.soft,alignItems:'center',justifyContent:'center'}}><Ionicons name={s.icon as any} size={22} color={on?colors.onInk:colors.ink}/></View><Text numberOfLines={2} style={{fontFamily:fonts.bodyBold,fontSize:12,textAlign:'center',color:colors.text}}>{hi?s.name_hi:s.name}</Text></Pressable>;})}</View>
    {services.length>SHOWN&&<Pressable accessibilityRole="button" onPress={()=>setMore(!more)} style={{minHeight:44,justifyContent:'center',alignItems:'center'}}><Text style={{fontFamily:fonts.bodyBold,fontSize:15,color:colors.accentText}}>{t(more?'fewerServices':'moreServices')}</Text></Pressable>}</View>}
   <View style={{flexDirection:'row',backgroundColor:colors.white,borderRadius:14,padding:4,borderWidth:1,borderColor:colors.line}}>{(['work','workers'] as const).map(k=><Pressable key={k} accessibilityRole="tab" accessibilityState={{selected:tab===k}} onPress={()=>setTab(k)} style={{flex:1,minHeight:44,borderRadius:11,alignItems:'center',justifyContent:'center',backgroundColor:tab===k?colors.ink:'transparent'}}><Text style={{fontFamily:fonts.bodyBold,fontSize:15,color:tab===k?colors.onInk:colors.muted}}>{t(k==='work'?'latestJobs':'listedWorkers')}</Text></Pressable>)}</View>
   <ErrorBox code={error}/>
   {items&&items.length===0&&!error&&<Empty text={t(tab==='work'?'noOpenJobs':'noListedWorkers')}/>}
   {tab==='work'&&items?.map((j,i)=><Card key={i}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{fontFamily:fonts.bodyBold,fontSize:18,color:colors.text,flex:1}}>{hi?j.service_name_hi:j.service_name}</Text>{j.wage_paise!=null&&<Text style={{fontFamily:fonts.display,fontSize:24,color:colors.ink}}>{'₹'+Math.round(j.wage_paise/100)}<Text style={{fontFamily:fonts.body,fontSize:13,color:colors.muted}}>{' '+t('perDay')}</Text></Text>}</View><Copy>{[j.locality,t(j.engagement_type)].filter(Boolean).join(' · ')}</Copy><Copy>{t('startedOn')+' '+new Date(j.start_at).toLocaleString()+' · '+j.slots_left+' '+t('slotsLeft')}</Copy><Button label={t('signUpToApply')} onPress={register}/></Card>)}
   {tab==='workers'&&items?.map((w,i)=><Card key={i}><View style={{flexDirection:'row',alignItems:'center',gap:8}}><Ionicons name="shield-checkmark-outline" size={20} color={colors.accentText}/><Text style={{fontFamily:fonts.bodyBold,fontSize:18,color:colors.text}}>{w.first_name}</Text></View><Copy>{(hi?w.skills_hi:w.skills).join(', ')}</Copy><Copy>{[w.area,w.experience_years+' '+t('experienceShort')].filter(Boolean).join(' · ')}</Copy><Copy>{(w.trust.average!==null?w.trust.average+'/5 ('+w.trust.reviews+' '+t('reviewsWord')+')':t('noReviewsYet'))+(w.online?' · '+t('availableNow'):'')}</Copy><Button label={t('signUpToHire')} onPress={register}/></Card>)}
   <View style={{gap:12}}><Text style={{fontFamily:fonts.bodyBold,fontSize:18,color:colors.text}}>{t('offerTitle')}</Text>{OFFERS.map(([icon,title,copy])=><View key={title} style={{flexDirection:'row',gap:14,alignItems:'flex-start',backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:16,padding:16}}><View style={{width:40,height:40,borderRadius:20,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center'}}><Ionicons name={icon as any} size={22} color={colors.ink}/></View><View style={{flex:1,gap:4}}><Text style={{fontFamily:fonts.bodyBold,fontSize:16,color:colors.text}}>{t(title)}</Text><Text style={{fontFamily:fonts.body,fontSize:14,lineHeight:21,color:colors.muted}}>{t(copy)}</Text></View></View>)}</View>
   <View style={{gap:12,backgroundColor:colors.ink,borderRadius:18,padding:18}}><Text style={{fontFamily:fonts.bodyBold,fontSize:13,color:colors.accent}}>{t('marketKicker')}</Text><Text style={{fontFamily:fonts.display,fontSize:26,lineHeight:32,color:colors.onInk}}>{t('marketTitle')}</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:10}}>{STATS.map(x=><Pressable key={x.k} accessibilityRole="link" accessibilityLabel={x.v+' '+t(x.k)} onPress={()=>Linking.openURL(x.url).catch(()=>{})} style={{width:200,minHeight:150,justifyContent:'space-between',gap:10,borderRadius:14,padding:14,backgroundColor:'#1C1E20'}}><Text style={{fontFamily:fonts.display,fontSize:30,color:colors.onInk}}>{x.v}</Text><Text style={{fontFamily:fonts.body,fontSize:13,lineHeight:19,color:'#D7DADC'}}>{t(x.k)}</Text><Text style={{fontFamily:fonts.body,fontSize:11,color:'#A9AFB4'}}>{x.src}</Text></Pressable>)}</ScrollView></View>
   <View style={{gap:10,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:18,backgroundColor:colors.white}}><Text style={{fontFamily:fonts.bodyBold,fontSize:13,color:colors.accentText}}>{t('sinceKicker')}</Text><Text style={{fontFamily:fonts.display,fontSize:24,lineHeight:30,color:colors.text}}>{t('sinceTitle')}</Text><Copy>{t('sinceCopy')}</Copy><Button secondary label={t('followInstagram')} onPress={()=>Linking.openURL(INSTAGRAM).catch(()=>{})}/></View>
   <Card><Text style={{fontFamily:fonts.bodyBold,fontSize:18,color:colors.text}}>{t('aboutTitle')}</Text><Copy>{t('aboutCopy')}</Copy><Copy>{'1. '+t('how1')}</Copy><Copy>{'2. '+t('how2')}</Copy><Copy>{'3. '+t('how3')}</Copy></Card>
  </ScrollView>
  <View style={{position:'absolute',left:0,right:0,bottom:0,flexDirection:'row',gap:12,padding:16,paddingBottom:Math.max(insets.bottom,12),backgroundColor:colors.white,borderTopWidth:1,borderTopColor:colors.line}}><View style={{flex:1}}><Button secondary label={t('signIn')} onPress={()=>router.push('/(public)/login')}/></View><View style={{flex:1}}><Button label={t('createAccount')} onPress={register}/></View></View>
 </SafeAreaView>;}
